# ==============================================================================
# Example docker-compose.overrides.yml file
#
# To use this file place it at the project along side docker-compose.yml
# renaming it to docker-compose.overrides.yml
#
# This example shows all possible environment variable and build argument
# overrides as if they were loaded from an .env file. Please see the example.env
# file for details on what each setting/value does.
#
# ==============================================================================

version: "3"

services:
    nginx:
        build:
            args:
                # Set the nginx versions and brotli commit values from the .env file
                - NGINX_BROTLI_COMMIT=${NGINX_BROTLI_COMMIT}
                - NGINX_VERSION=${NGINX_VERSION}


    php:
        environment:
            # Set the application environment in use from the .env file
            - APP_ENV=${APP_ENV}
